import { Provider } from 'web3/providers'
import './globals.css'
import Providers from './Provider'
import AppBar from './AppBar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppBar />
          {children}</Providers>
        </body>
    </html>
  )
}
